name: PVS-Studio
on: workflow_dispatch
jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
          category: PVS-Studio
